project:
  type: website

website:
  title: "ISSS608-VAA"
  navbar:
    left:
      - text: "In-Class Exercises"
        menu: 
          - text: "In-Class Exercise 1"
            href: "In_Class_Exercise/In_Class_Ex01/In_Class_Ex01.html"
          - text: "In-Class Exercise 7"
            href: "In_Class_Exercise/In_Class_Ex07/In_Class_Ex07.html"
      - text: "Hands-On Exercises"
        menu: 
          - text: "1A. ggplot2 Methods"
            href: "Hands_On_Exercise/Hands_On_Ex01/Hands_On_Ex01.html"
          - text: "2A. Beyond ggplot2 Fundamentals"
            href: "Hands_On_Exercise/Hands_On_Ex02/Hands_On_Ex02.html"
          - text: "3A. Interactive Data Visualisation"
            href: "Hands_On_Exercise/Hands_On_Ex03A/Hands_On_Ex03A.html"
          - text: "3B. Animated Statistical Graphics"
            href: "Hands_On_Exercise/Hands_On_Ex03B/Hands_On_Ex03B.html"
          - text: "4A. Visualising Distribution"
            href: "Hands_On_Exercise/Hands_On_Ex04A/Hands_On_Ex04A.html"
          - text: "4B. Visualising Statistical Analysis"
            href: "Hands_On_Exercise/Hands_On_Ex04B/Hands_On_Ex04B.html"
          - text: "4C. Visualising Uncertainty"
            href: "Hands_On_Exercise/Hands_On_Ex04C/Hands_On_Ex04C.html"
          - text: "4D. Visualising Funnel Plots"
            href: "Hands_On_Exercise/Hands_On_Ex04D/Hands_On_Ex04D.html"
          - text: "5A. Ternary Plot"
            href: "Hands_On_Exercise/Hands_On_Ex05A/Hands_On_Ex05A.html"
          - text: "5B. Visual Correlation Analysis"
            href: "Hands_On_Exercise/Hands_On_Ex05B/Hands_On_Ex05B.html"
          - text: "5C. Multivariate Analysis with Heatmap"
            href: "Hands_On_Exercise/Hands_On_Ex05C/Hands_On_Ex05C.html"
          - text: "5D. Multivariate Analysis with Parallel Coordinates Plot"
            href: "Hands_On_Exercise/Hands_On_Ex05D/Hands_On_Ex05D.html"
          - text: "5E. Treemap Visualisation"
            href: "Hands_On_Exercise/Hands_On_Ex05E/Hands_On_Ex05E.html"
          - text: "6A. Visualising Time-Oriented Data"
            href: "Hands_On_Exercise/Hands_On_Ex06/Hands_On_Ex06.html"
          - text: "8A. Choropleth Mapping"
            href: "Hands_On_Exercise/Hands_On_Ex08A/Hands_On_Ex08A.html"
          - text: "8B. Visualising Geospatial Point Data"
            href: "Hands_On_Exercise/Hands_On_Ex08B/Hands_On_Ex08B.html"
          - text: "8C. Analytical Mapping"
            href: "Hands_On_Exercise/Hands_On_Ex08C/Hands_On_Ex08C.html"
            
      - text: "Take-Home Exercises"
        menu:
          - text: "Take-Home Exercise 1"
            href: "Take_Home_Exercise/Take_Home_Ex01/Take_Home_Ex01.html"
          - text: "Take-Home Exercise 2"
            href: "Take_Home_Exercise/Take_Home_Ex02/Take_Home_Ex02.html"
          - text: "Take-Home Exercise 3"
            href: "Take_Home_Exercise/Take_Home_Ex03/Take_Home_Ex03.html"
          - text: "Take-Home Exercise 4"
            href: "Take_Home_Exercise/Take_Home_Ex04/Take_Home_Ex04.html"
            
    right: 
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: lightly
    css: styles.css
    toc: true

editor: visual

