project:
  type: website

website:
  title: "ISSS608-VAA"
  navbar:
    left:
      - text: "In-Class Exercises"
        menu: 
          - text: "In-Class Exercise 1"
            href: "In_Class_Exercise/In_Class_Ex01/In_Class_Ex01.html"
      - text: "Hands-On Exercises"
        menu: 
          - text: "Hands-on Exercise 1"
            href: "Hands_On_Exercise/Hands_On_Ex01/Hands_On_Ex01.html"
          - text: "Hands-On Exercise 2"
            href: "Hands_On_Exercise/Hands_On_Ex02/Hands_On_Ex02.html"
      - text: "Take-Home Exercises"
        menu:
          - text: "Take-Home Exercise 1"
            href: "Take_Home_Exercise/Take_Home_Ex01/Take_Home_Ex01.html"
    right: 
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: lightly
    css: styles.css
    toc: true

editor: visual

